services:
  nextjs-lms-alfurqon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-lms-alfurqon
    restart: unless-stopped
    ports:
      - "3031:3031"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true