services:
  nextjs-lms-alfurqon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-lms-alfurqon
    restart: unless-stopped
    ports:
      - "3031:3031"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/dev.db
    volumes:
      - ./prisma:/app/prisma
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true